name: Daily Auto Commit

on:
  schedule:
    - cron: "30 18 * * *"   # Runs daily at 12:00 AM IST
  workflow_dispatch:

permissions:
  contents: write   #  THIS gives push permission

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a daily change
        run: |
          echo "Last updated on $(date)" >> daily-log.txt

      - name: Commit and Push
        run: |
          git config user.name "tanmaydwivedi1"
          git config user.email "tanmaydwivedi28@gmail.com"
          git add .
          git commit -m "Daily auto commit" || echo "No changes to commit"
          git push
